name: Lint
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install packages
        run: pip install -r dev-requirements.txt

      - name: Install pre-commit hooks
        run: pre-commit install --install-hooks

      - name: Run pre-commit
        run: pre-commit run --all-files
